asset/urls.py
from django.urls import path
from . import views

app_name    = "asset"
urlpatterns = [
    path('', views.index, name="index"),
    path('delete/<int:pk>/', views.delete, name="delete"),
]

bbs/urls.py
from django.urls import path
from . import views

app_name    = "bbs"
urlpatterns = [
    path('', views.index, name="index"),
    path('delete/<int:pk>/', views.delete, name="delete"),
]

config/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("asset.urls")),
    path('accounts/', include('allauth.urls')),
]

asset/models.py
from django.db import models
from django.utils import timezone


class Category(models.Model):
    class Meta:
        db_table = "category"

    name = models.CharField(verbose_name="カテゴリ名",max_length=100)
    dt =models.DateTimeField(verbose_name="追加日", default=timezone.now)

    def __str__(self):
        return self.name

class Balance(models.Model):

    class Meta:
        db_table = "balance"

    category = models.ForeignKey(Category,verbose_name="カテゴリ",on_delete=models.CASCADE,blank=True, null=True)

    title = models.CharField(verbose_name="タイトル", max_length=100, default="")
    comment = models.CharField(verbose_name="コメント", blank=True, max_length=2000)
    income = models.IntegerField(verbose_name="収入", default=0)
    spending = models.IntegerField(verbose_name="支出", default=0)
    dt = models.DateTimeField(verbose_name="投稿日", default=timezone.now)
    pay_dt  =  models.DateTimeField(verbose_name="決済日")

    def __str__(self):
        return self.comment

bbs/models.py
from django.db import models
from django.utils import timezone


class Category(models.Model):
    class Meta:
        db_table = "category"

    name = models.CharField(verbose_name="カテゴリ名",max_length=100)
    dt =models.DateTimeField(verbose_name="追加日", default=timezone.now)

    def __str__(self):
        return self.name

class Topic(models.Model):

    class Meta:
        db_table = "topic"

    category = models.ForeignKey(Category,verbose_name="カテゴリ",on_delete=models.CASCADE,blank=True, null=True)


    title = models.CharField(verbose_name="タイトル", max_length=100, default="")
    comment = models.CharField(verbose_name="コメント", blank=True, max_length=2000)
    income = models.IntegerField(verbose_name="収入", default=0)
    spending = models.IntegerField(verbose_name="支出", default=0)
    dt = models.DateTimeField(verbose_name="投稿日", default=timezone.now)
    pay_dt  =  models.DateTimeField(verbose_name="決済日")

    def __str__(self):
        return self.comment

asset/forms.py
from django import forms
from .models import Balance

class BalanceForm(forms.ModelForm):
    class Meta:
        model     = Balance
        fields   = [ "category","title","comment","income","spending","pay_dt"]

bbs/forms.py
from django import forms
from .models import Topic

class TopicForm(forms.ModelForm):
    class Meta:
        model     = Topic
        fields   = [ "category","title","comment","income","spending","pay_dt"]

asset/views.py
from django.shortcuts import render,redirect
from django.views import View

from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Balance,Category
from .forms import BalanceForm

from django.db.models import Q

class BalanceView(LoginRequiredMixin,View):

    def get(self, request, *args, **kwargs):

        categories  = Category.objects.all()

        if "search" in request.GET:

            if request.GET["search"] == "" or request.GET["search"].isspace():
                return redirect("asset:index")

            search      = request.GET["search"].replace(" ","　")
            search_list =search.split(" ")

            query       = Q()
            for word in search_list:

                query &= Q(title__contains=word)

            balances  = Balance.objects.filter(query)
        else:
            balances  = Balance.objects.all()


        balances      = list(balances.values())


        total       = 0
        for balance in balances:

            total          = total + int(balance["income"]) - int(balance["spending"])
            balance["total"] = total

            if balance["category_id"]:
                category            = Category.objects.filter(id=balance["category_id"]).first()
                balance["category"] = category.name

        context = { "balances":balances,
                    "categories":categories,
                   }

        return render(request,"asset/index.html",context)

    def post(self, request, *args, **kwargs):

        form = BalanceForm(request.POST)

        if form.is_valid():
            print("バリデーションOK")
            form.save()
        else:
            print("バリデーションNG")

        return redirect("asset:index")

index   = BalanceView.as_view()

class BalanceDeleteView(LoginRequiredMixin,View):

    def post(self,request, pk, *args, **kwargs):

        balance = Balance.objects.filter(id=pk).first()
        balance.delete()

        return redirect("asset:index")

delete = BalanceDeleteView.as_view()


bbs/views.py
from django.shortcuts import render,redirect
from django.views import View

from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Topic,Category
from .forms import TopicForm

from django.db.models import Q

class BbsView(LoginRequiredMixin,View):

    def get(self, request, *args, **kwargs):

        categories  = Category.objects.all()

        if "search" in request.GET:

            if request.GET["search"] == "" or request.GET["search"].isspace():
                return redirect("bbs:index")

            search      = request.GET["search"].replace(" ","　")
            search_list =search.split(" ")

            query       = Q()
            for word in search_list:

                query &= Q(title__contains=word)


            topics  = Topic.objects.filter(query)
        else:
            topics  = Topic.objects.all()


        topics      = list(topics.values())


        total       = 0
        for topic in topics:

            total          = total + int(topic["income"]) - int(topic["spending"])
            topic["total"] = total

            if topic["category_id"]:
                category            = Category.objects.filter(id=topic["category_id"]).first()
                topic["category"]   =category.name


        chobos = []
        context = {"chobos":chobos,
                   "balances":topics,
                   "categories":categories,
                   }

        return render(request,"bbs/index.html",context)

    def post(self, request, *args, **kwargs):

        form = TopicForm(request.POST)

        if form.is_valid():
            print("バリデーションOK")
            form.save()
        else:
            print("バリデーションNG")

        return redirect("bbs:index")

index   = BbsView.as_view()

class BbsDeleteView(LoginRequiredMixin,View):

    def post(self,request, pk, *args, **kwargs):

        topic = Topic.objects.filter(id=pk).first()
        topic.delete()

        return redirect("bbs:index")

delete = BbsDeleteView.as_view()

# Create your views here.

templates/asset/index.html
{% load static %}

<html xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>

    <!--日本語化用JS-->
    <script src="https://cdn.jsdelivr.net/npm/flatpickr/dist/l10n/ja.js"></script>

    <!-- cssは一部が不具合を起こしているようなので、全て書き換え-->
    <link rel="stylesheet" href="{% static 'asset/css/style.css' %}">
    <script src="{% static 'asset/js/script.js' %}"></script>

    <!--fontawesomeは
        https://fontawesome.com/download#pro-packages
        からFreeforWeb(CSSやJSが含まれている方)をDLして
        css(fontawesomeに改名)とwebfontをcommon/css/に配置
    -->

    <link rel="stylesheet" href="{% static 'common/css/fontawesome/all.min.css' %}">

    <style>
        body{
            background-image: url("{% static 'asset/img/ookamikun1.png' %}");
            background-attachment: fixed;
            background-size: cover;
            background-position: right 10% bottom 10%;
            }
    </style>
</head>
<body>

    <header>
        <input id="l_sidebar" class="l_sidebar_button" type="checkbox">
        <div class="left_header">
        <label class="l_sidebar_label" for="l_sidebar">
                <i class="fas fa-bars"></i>
                <i class="fas fa-times"></i>
            </label>
            <a class="header_link" href="{% url 'asset:index' %}"><h1>メニュー</h1></a>
            <div class="header_right_content">
                <!--TODO:ここにログインのアイコンなどを-->
            </div>
        </div>
        <div class="l_sidebar_menu">

            <a href="{% url 'account_logout' %}">ログアウト</a>

        </div>
        <label class="l_sidebar_closer" for="l_sidebar"></label>
    </header>

<main>
    <h1 style="text-align: right">４月-April</h1>
    <form action="" method="get">
        <input type="text" name="search" placeholder="検索したいワード" value="{{ request.GET.search }}">
        <input type="submit" class="btn btn-outline-dark" value="検索">
    </form>
    <form action="" method="post">
    {% csrf_token %}

        <select name="category">
            <option value="">カテゴリを選んでください</option>
            {% for category in categories %}
            <option value="{{ category.id }}">{{ category.name }}</option>
            {% endfor %}
        </select>
        <input type="text" name="title" placeholder="鑑定科目を入力してください" required>
        <input type="text" name="comment" placeholder="主な用途を入力してください" value=" ">
        <input type="number" name="income" value="0">
        <input type="number" name="spending" value="0">
        <input id="pay_dt" type="text" name="pay_dt" readonly>
        <input class="btn btn-success" type="submit" value="投稿">
    </form>

    <select id="" name="">
        <option value=""></option>
    </select>



    <input id="tab_radio_0" class="tab_radio" type="radio" name="tab_system" checked><label class="tab_label" for="tab_radio_0">1年表示</label>
    <input id="tab_radio_1" class="tab_radio" type="radio" name="tab_system"><label class="tab_label" for="tab_radio_1">1月</label>
    <input id="tab_radio_2" class="tab_radio" type="radio" name="tab_system"><label class="tab_label" for="tab_radio_2">2月</label>
    <input id="tab_radio_3" class="tab_radio" type="radio" name="tab_system"><label class="tab_label" for="tab_radio_3">3月</label>
    <input id="tab_radio_4" class="tab_radio" type="radio" name="tab_system"><label class="tab_label" for="tab_radio_4">4月</label>
    <input id="tab_radio_5" class="tab_radio" type="radio" name="tab_system"><label class="tab_label" for="tab_radio_5">5月</label>
    <input id="tab_radio_6" class="tab_radio" type="radio" name="tab_system"><label class="tab_label" for="tab_radio_6">6月</label>
    <input id="tab_radio_7" class="tab_radio" type="radio" name="tab_system"><label class="tab_label" for="tab_radio_7">7月</label>
    <input id="tab_radio_8" class="tab_radio" type="radio" name="tab_system"><label class="tab_label" for="tab_radio_8">8月</label>
    <input id="tab_radio_9" class="tab_radio" type="radio" name="tab_system"><label class="tab_label" for="tab_radio_9">9月</label>
    <input id="tab_radio_10" class="tab_radio" type="radio" name="tab_system"><label class="tab_label" for="tab_radio_10">10月</label>
    <input id="tab_radio_11" class="tab_radio" type="radio" name="tab_system"><label class="tab_label" for="tab_radio_11">11月</label>
    <input id="tab_radio_12" class="tab_radio" type="radio" name="tab_system"><label class="tab_label" for="tab_radio_12">12月</label>

    <div id="tab_area_0" class="tab_area">1年表示</div>
    <div id="tab_area_1" class="tab_area">1月</div>
    <div id="tab_area_2" class="tab_area">2月</div>
    <div id="tab_area_3" class="tab_area">3月</div>
    <div id="tab_area_4" class="tab_area">4月</div>
    <div id="tab_area_5" class="tab_area">5月</div>
    <div id="tab_area_6" class="tab_area">6月</div>
    <div id="tab_area_7" class="tab_area">7月</div>
    <div id="tab_area_8" class="tab_area">8月</div>
    <div id="tab_area_9" class="tab_area">9月</div>
    <div id="tab_area_10" class="tab_area">10月</div>
    <div id="tab_area_11" class="tab_area">11月</div>
    <div id="tab_area_12" class="tab_area">12月</div>


    {% include "asset/table.html" %}
    </main>
</body>
</html>

templates/asset/table.html
{% load humanize %}

<table class="table table-striped">
    <thead class="table-dark">
        <tr>
            <td class="text-center">id</td>
            <td class="text-center">カテゴリ</td>
            <td class="text-center">鑑定項目</td>
            <td class="text-center">主な用途</td>
            <td class="text-center">収入金額</td>
            <td class="text-center">支出金額</td>
            <td class="text-center">小計</td>
            <td class="text-center">登録日</td>
            <td class="text-center">決算日</td>
            <td></td>
        </tr>
    </thead>

    <tbody>
    {% for balance in balances %}
    <tr>
        <td>{{ balance.id }}</td>
        <td>{{ balance.category|default:"未分類" }}</td>
        <td>{{ balance.title }}</td>
        <td>{{ balance.comment }}</td>
        <td>{{ balance.income|default:"0"|intcomma }}</td>
        <td>{{ balance.spending|default:"0"|intcomma }}</td>
        <td>{{ balance.total|default:"0"|intcomma }}</td>
        <td>{{ balance.dt }}</td>
        <td>{{ balance.pay_dt }}</td>
        <td>
           <form action="{% url 'asset:delete' balance.id %}" method="POST">
               {% csrf_token %}
               <input class="btn btn-outline-dark" type="submit" value="削除">
           </form>
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>

templates/bbs/index.html
{% load static %}
{% load table %}

<html xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>

    <!--日本語化用JS-->
    <script src="https://cdn.jsdelivr.net/npm/flatpickr/dist/l10n/ja.js"></script>

    <!-- cssは一部が不具合を起こしているようなので、全て書き換え-->
    <link rel="stylesheet" href="{% static 'bbs/css/style.css' %}">
    <script src="{% static 'bbs/js/script.js' %}"></script>

    <!--fontawesomeは
        https://fontawesome.com/download#pro-packages
        からFreeforWeb(CSSやJSが含まれている方)をDLして
        css(fontawesomeに改名)とwebfontをcommon/css/に配置
    -->

    <link rel="stylesheet" href="{% static 'common/css/fontawesome/all.min.css' %}">

    <style>
        body{
            background-image: url("{% static 'bbs/img/ookamikun1.png' %}");
            background-attachment: fixed;
            background-size: cover;
            background-position: right 10% bottom 10%;
            }
    </style>
</head>
<body>

    <header>
        <input id="l_sidebar" class="l_sidebar_button" type="checkbox">
        <div class="left_header">
        <label class="l_sidebar_label" for="l_sidebar">
                <i class="fas fa-bars"></i>
                <i class="fas fa-times"></i>
            </label>
            <a class="header_link" href="{% url 'bbs:index' %}"><h1>メニュー</h1></a>
            <div class="header_right_content">
                <!--TODO:ここにログインのアイコンなどを-->
            </div>
        </div>
        <div class="l_sidebar_menu">

            <a href="{% url 'account_logout' %}">ログアウト</a>

        </div>
        <label class="l_sidebar_closer" for="l_sidebar"></label>
    </header>

<main>
    <h1 style="text-align: right">４月-April</h1>
    <form action="" method="get">
        <input type="text" name="search" placeholder="検索したいワード" value="{{ request.GET.search }}">
        <input type="submit" class="btn btn-outline-dark" value="検索">
    </form>
    <form action="" method="post">
    {% csrf_token %}

        <select name="category">
            <option value="">カテゴリを選んでください</option>
            {% for category in categories %}
            <option value="{{ category.id }}">{{ category.name }}</option>
            {% endfor %}
        </select>
        <input type="text" name="title" placeholder="鑑定科目を入力してください" required>
        <input type="text" name="comment" placeholder="主な用途を入力してください" value=" ">
        <input type="number" name="income" value="0">
        <input type="number" name="spending" value="0">
        <input id="pay_dt" type="text" name="pay_dt" readonly>
        <input class="btn btn-success" type="submit" value="投稿">
    </form>
   {# {% generate_balance topics %} #}

    {% include "bbs/table.html"%}
    </main>
</body>
</html>

templates/bbs/table.html
{% load humanize %}

<table class="table table-striped">
    <thead class="table-dark">
        <tr>
            <td class="text-center">id</td>
            <td class="text-center">カテゴリ</td>
            <td class="text-center">鑑定項目</td>
            <td class="text-center">主な用途</td>
            <td class="text-center">収入金額</td>
            <td class="text-center">支出金額</td>
            <td class="text-center">残高</td>
            <td class="text-center">登録日</td>
            <td class="text-center">決算日</td>
            <td></td>
        </tr>
    </thead>

    <tbody>
    {% for balance in balances %}
    <tr>
        <td>{{ balance.id }}</td>
        <td>{{ balance.category|default:"未分類" }}</td>
        <td>{{ balance.title }}</td>
        <td>{{ balance.comment }}</td>
        <td>{{ balance.income|default:"0"|intcomma }}</td>
        <td>{{ balance.spending|default:"0"|intcomma }}</td>
        <td>{{ balance.total|default:"0"|intcomma }}</td>
        <td>{{ balance.dt }}</td>
        <td>{{ balance.pay_dt }}</td>
        <td>
           <form action="{% url 'bbs:delete' balance.id %}" method="POST">
               {% csrf_token %}
               <input class="btn btn-outline-dark" type="submit" value="削除">
           </form>
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>